// 玩家畫像監控設定（非典型 CRUD，為設定頁，整包讀取/儲存）
// 欄位沿用舊後端 /backend/bot/config 回傳結構
interface IPSettingItem {
  area: string;
  note: string;
}

interface TagScoreItem {
  tagID?: number;
  score?: number;
}

interface PortraitConfig {
  // 關聯帳號
  portraitDeviceEnable?: boolean;
  portraitDeviceMonths?: number;
  portraitIPEnable?: boolean;
  portraitIPMonths?: number;
  // 登入監控
  onlineLoginTimeEnable?: boolean;
  onlineLoginTime?: number;
  onlineLoginRangeEnable?: boolean;
  onlineLoginRange?: number;
  onlineLoginRangeCount?: number;
  onlineDayTimeEnable?: boolean;
  onlineDayTime?: number;
  loginRiskIPChinaExceptEnable?: boolean;
  loginRiskIPSettingEnable?: boolean;
  loginRiskIPSetting?: IPSettingItem[];
  // 對沖監控
  hedgingLiveContextAEnabled?: boolean;
  hedgingLiveContextBEnabled?: boolean;
  hedgingSportContextBEnabled?: boolean;
  hedgingLiveMinBetAmount?: number;
  hedgingLivePassMemberTags?: any;
  hedgingLiveCoefficientPerfect?: number;
  hedgingLiveCoefficientPartial?: number;
  // 投注行為
  monitorSportCornersEnable?: boolean;
  monitorSportCornersDay?: number;
  monitorSportCornersPercent?: number;
  monitorSportCornersPercentRemove?: number;
  monitorSportCorrectScoreEnable?: boolean;
  monitorSportCorrectScoreDay?: number;
  monitorSportCorrectScorePercent?: number;
  monitorSportCorrectScorePercentRemove?: number;
  monitorSportComboEnable?: boolean;
  monitorSportComboDay?: number;
  monitorSportComboPercent?: number;
  monitorSportComboTotalBet?: number;
  monitorSportComboTotalBetAmount?: number;
  monitorSportComboPercentRemove?: number;
  monitorSportInPlayEnable?: boolean;
  monitorSportInPlayDay?: number;
  monitorSportInPlayPercent?: number;
  monitorSportInPlayPercentRermove?: number;
  monitorSportInPlayTotalBet?: number;
  monitorSportInPlayTotalBetAmount?: number;
  monitorSportEarlyEnable?: boolean;
  monitorSportEarlyDay?: number;
  monitorSportEarlyPercent?: number;
  monitorSportEarlyPercentRemove?: number;
  monitorSportEarlyTotalBet?: number;
  monitorSportEarlyTotalBetAmount?: number;
  monitorSportMixEnable?: boolean;
  monitorSportMixDay?: number;
  monitorSportMixInPlayPercent?: number;
  monitorSportMixEarlyPercent?: number;
  monitorSportMixBothLowPercent?: number;
  monitorSportMixTotalBet?: number;
  monitorSportMixTotalBetAmount?: number;
  monitorSportMixAnyoneHigherPercentRemove?: number;
  monitorSportMixBothHigherPercentRemove?: number;
  monitorSportNonSoccerBasketballEnable?: boolean;
  monitorSportNonSoccerBasketballDay?: number;
  monitorSportNonSoccerBasketballPercent?: number;
  monitorSportNonSoccerBasketballPercentRemove?: number;
  monitorSportBasketballQuarterEnable?: boolean;
  monitorSportBasketballQuarterDay?: number;
  monitorSportBasketballQuarterPercent?: number;
  monitorSportBasketballQuarterPercentRemove?: number;
  monitorSportBasketballQuarterTotalBet?: number;
  monitorSportBasketballQuarterTotalBetAmount?: number;
  monitorSportLowOddsEnable?: boolean;
  monitorSportLowOddsDay?: number;
  monitorSportLowOddsWAOAdd?: number;
  monitorSportLowOddsWAORemove?: number;
  monitorSportLowOddsTotalBet?: number;
  monitorSportLowOddsTotalBetAmount?: number;
  monitorSportHighOddsEnable?: boolean;
  monitorSportHighOddsDay?: number;
  monitorSportHighOddsWAOAdd?: number;
  monitorSportHighOddsWAORemove?: number;
  monitorSportHighOddsTotalBet?: number;
  monitorSportHighOddsTotalBetAmount?: number;
  // 風控相關
  monitorSportNonIntBetEnable?: boolean;
  monitorSportNonIntBetDay?: number;
  monitorSportNonIntBetPercent?: number;
  monitorSportSameBetItemEnable?: boolean;
  monitorSportSameBetItemDay?: number;
  monitorSportSameBetItemCount?: number;
  monitorSportSameBetItemPercent?: number;
  monitorSportSameBetItemReplenishEnable?: boolean;
  monitorSportSameBetItemReplenishDay?: number;
  monitorSportSameBetItemReplenishCount?: number;
  monitorSportSameBetItemReplenishMultiple?: number;
  monitorSportSameBetItemReplenishMinAmount?: number;
  monitorSportSameBetItemReplenishPercent?: number;
  monitorSportBetRejectEnable?: boolean;
  monitorSportBetRejectDay?: number;
  monitorSportBetRejectPercent?: number;
  monitorSportGroupBetSuspectedEnable?: boolean;
  monitorSportGroupBetSuspectedDay?: number;
  monitorSportGroupBetSuspectedPeople?: number;
  monitorSportGroupBetSuspectedMinute?: number;
  monitorSportGroupBetSuspectedOtherMatch?: number;
  monitorSportGroupBetEnable?: boolean;
  monitorSportGroupBetDay?: number;
  monitorSportGroupBetPeople?: number;
  monitorSportGroupBetMinute?: number;
  monitorSportGroupBetOtherMatch?: number;
  monitorWeekdaysBetEnable?: boolean;
  monitorWeekdaysBetDay?: number;
  monitorWeekdaysBetPercent?: number;
  monitorHolidayBetEnable?: boolean;
  monitorHolidayBetDay?: number;
  monitorHolidayBetPercent?: number;
  monitorPcUserEnable?: boolean;
  monitorPcUserDay?: number;
  monitorPcUserPercent?: number;
  monitorH5UserEnable?: boolean;
  monitorH5UserDay?: number;
  monitorH5UserPercent?: number;
  monitorProfitEnable?: boolean;
  monitorProfitDay?: number;
  monitorNetProfitDay?: number;
  monitorProfitKill?: number;
  // 團體&工作室
  tagScoreEnable?: boolean;
  tagScoreThreshold?: number;
  tagScoreItems?: TagScoreItem[];
}

export type { IPSettingItem, TagScoreItem, PortraitConfig };
